default_language_version:
  python: python3.13

repos:
  - repo: git@github.com:pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
      # list of supported hooks: https://pre-commit.com/hooks.html
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files

  # REPLACED: black, isort, pyupgrade, flake8 with ruff (uses your pyproject.toml config)
  - repo: git@github.com:astral-sh/ruff-pre-commit.git
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix] # Auto-fix issues where possible
      - id: ruff-format # Replaces black formatting

  # python security linter - FIXED: Added pbr dependency
  - repo: git@github.com:PyCQA/bandit.git
    rev: "1.7.5"
    hooks:
      - id: bandit
        args: ["-s", "B101"]
        additional_dependencies: [pbr]

  # yaml formatting
  - repo: git@github.com:pre-commit/mirrors-prettier.git
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier
        types: [yaml]
        exclude: "environment.yaml"

  # shell scripts linter
  - repo: git@github.com:shellcheck-py/shellcheck-py.git
    rev: v0.9.0.2
    hooks:
      - id: shellcheck

  # md formatting - FIXED: Removed problematic mdformat-gfm plugin
  - repo: git@github.com:executablebooks/mdformat.git
    rev: 0.7.16
    hooks:
      - id: mdformat
        args: ["--number"]
        additional_dependencies:
          - mdformat-tables
          - mdformat_frontmatter

  # word spelling linter
  - repo: git@github.com:codespell-project/codespell.git
    rev: v2.2.4
    hooks:
      - id: codespell
        args:
          - --skip=logs/**,data/**,*.ipynb

  # jupyter notebook cell output clearing
  - repo: git@github.com:kynan/nbstripout.git
    rev: 0.6.1
    hooks:
      - id: nbstripout

  # jupyter notebook linting - FIXED: Added setuptools for pkg_resources
  - repo: git@github.com:nbQA-dev/nbQA.git
    rev: 1.6.3
    hooks:
      - id: nbqa-ruff
        args: [--fix]
        additional_dependencies: [ruff, setuptools]
